apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume2
spec:
  storageClassName: voor-databases
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/volume2