apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
spec:
  storageClassName: voor-databases
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/volume1